services:
  - type: web
    name: poker-trivia-frontend
    env: node
    plan: starter
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
